### ISSUE TITLE
Using dataverse-webapi: Module '"dataverse-webapi/lib/node"' has no exported member 'parseGuid'

### ISSUE THREAD

**Issue by datenshi** [derekfinlinson/powerapps-tools#5]
I get the error: Module '"dataverse-webapi/lib/node"' has no exported member 'parseGuid', when I just try to use the example code in a clean TS project.

Is there anything I am missing?

Thanks.

**Comment by derekfinlinson** [comment]
That function has been moved to another package: https://github.com/derekfinlinson/powerapps-tools/blob/5951139d4b988b1c99671b555bba3ddafc81af8d/packages/powerapps-common/src/index.ts#L312. I'll update the README to remove it.
