### ISSUE TITLE
Batch Operation with relative path

### ISSUE THREAD

**Issue by nerumo** [derekfinlinson/powerapps-tools#7]
There's an issue with Odata batch operations. The current implementation sends absolute paths within the batch, but this failes because the dataverse expects an relative path like this:

![image](https://github.com/derekfinlinson/powerapps-tools/assets/8597645/4942e0b1-3bc9-4711-a18c-27d83c43a86d)

Thanks for this package and your cool ideas in this project

**Comment by nerumo** [comment]
This change fixes it:

![image](https://github.com/derekfinlinson/powerapps-tools/assets/8597645/e2e569aa-0b3f-43c5-bf59-819aa1d71e8c)

**Comment by derekfinlinson** [comment]
Fixed in 01c2608326d0db6c989ee8e6d6eef2731018cc29
